// src/components/AddForm.vue
<template>
  <div class="form-container" data-testid="addForm-container">
    <h2>
      Add To Initiative
      <toggle-switch
        name="Creature Type"
        :checked="isPlayer"
        @toggle-change="togglePlayer"
      />
    </h2>
    <form
      class="add-form"
      @submit.prevent="addToInit"
      data-testid="addForm-form"
    >
      <div class="form-input">
        <label for="new-name">Name of Creature:</label>
        <input
          class="input add-input"
          type="text"
          id="new-name"
          v-model="creatureName"
          @focus="(e) => e.target.select()"
        />
      </div>

      <div class="form-input number-input">
        <label for="init-roll">Initiative:</label>
        <input
          class="input add-input"
          type="number"
          id="init-roll"
          v-model="creatureInit"
          @focus="(e) => e.target.select()"
        />
      </div>

      <div v-if="isPlayer" class="form-input number-input">
        <label for="health">HP:</label>
        <input
          class="input add-input"
          type="number"
          id="health"
          v-model="creatureHP"
          @focus="(e) => e.target.select()"
        />
      </div>

      <input class="add-input" type="submit" value="Submit" />
    </form>
  </div>
</template>

<script>
import { ref } from "vue";
import { useStore } from "vuex";
import ToggleSwitch from "./ToggleSwitch.vue";

export default {
  components: { ToggleSwitch },
  name: "AddForm",
  setup() {
    const creatureName = ref("");
    const creatureInit = ref(1);
    const creatureHP = ref(1);
    const isPlayer = ref(false);

    const togglePlayer = () => {
      isPlayer.value = !isPlayer.value;
    };

    const store = useStore();

    const addToInit = () =>
      store.commit("addToOrder", {
        creaturesToAdd: [
          {
            isPlayer,
            name: creatureName,
            init: creatureInit,
            HP: creatureHP,
            id: Date.now()
          }
        ]
      });

    return {
      creatureName,
      creatureInit,
      creatureHP,
      isPlayer,
      addToInit,
      togglePlayer
    };
  }
};
</script>

<style>
.form-container {
  box-sizing: border-box;
  margin: auto;
  margin-top: 0;
  width: 95%;
  /* margin-bottom: 20px; */
  padding: 10px;
  position: sticky;
  border: var(--default-border);
  border-radius: var(--border-radius);
}

.form-input {
  width: fit-content;
}

.number-input {
  display: inline-block;
}

.add-input {
  display: inline-block;
  border-radius: 5px;
  border: 1px solid gray;
  margin: 0 5px;
}

.add-input[type="number"] {
  width: 20px;
}

.add-input[type="submit"] {
  display: block;
  margin: auto;
  width: 50%;
  font-size: 1.25rem;
  font-weight: bold;
  background: rgb(160, 26, 26);
  color: white;
  margin-top: 20px;
  border: 2px solid black;
}

@media only screen and (min-width: 400px) {
  .form-container {
    width: fit-content;
  }
  .add-input[type="number"] {
    width: 45px;
  }
}
</style>

// src/components/AddForm.tsx
import React, { useState } from 'react';
import { useInitContext } from '../context/initContext';
import { ContextType } from '../lib/types';
import '../styles/Form.css';
import { ToggleSwitch } from './ToggleSwitch';

export const AddForm = () => {
	const { addToOrder }: ContextType = useInitContext();

	const [isPlayer, togglePlayer] = useState(false);
	const [creatureName, setCreatureName] = useState('');
	const [creatureInit, setCreatureInit] = useState(1);
	const [creatureHP, setCreatureHP] = useState(1);

	function addToInit(e: any) {
		e.preventDefault();

		addToOrder([
			{
				name: creatureName,
				init: creatureInit,
				HP: creatureHP,
				isPlayer,
				id: Date.now(),
			},
		]);

		setCreatureName('');
		setCreatureInit(1);
		setCreatureHP(1);
	}

	return (
		<div className="form-container" data-testid="addForm-container">
			<h2>
				Add To Initiative
				<ToggleSwitch
					name="Creature Type"
					checked={isPlayer}
					onChange={() => togglePlayer(!isPlayer)}
				/>
			</h2>
			<form
				className="add-form"
				onSubmit={addToInit}
				data-testid="addForm-form">
				<div className="form-input">
					<label htmlFor="new-name">Name of Creature:</label>
					<input
						className="input add-input"
						type="text"
						id="new-name"
						value={creatureName}
						onChange={(e) => setCreatureName(e.target.value)}
						onFocus={(e) => e.target.select()}
					/>
				</div>

				<div className="form-input number-input">
					<label htmlFor="init-roll">Initiative:</label>
					<input
						className="input add-input"
						type="number"
						id="init-roll"
						value={creatureInit}
						onChange={(e) => setCreatureInit(parseInt(e.target.value))}
						onFocus={(e) => e.target.select()}
					/>
				</div>

				{!isPlayer && (
					<div className="form-input number-input">
						<label htmlFor="health">HP:</label>
						<input
							className="input add-input"
							type="number"
							id="health"
							value={creatureHP}
							onChange={(e) => setCreatureHP(parseInt(e.target.value))}
							onFocus={(e) => e.target.select()}
						/>
					</div>
				)}

				<input className="add-input" type="submit" value="Submit" />
			</form>
		</div>
	);
};
