// src/components/CreatureTracker.tsx
import React from 'react';
import { Creature } from '../lib/types';
import '../styles/Tracker.css';

interface Props {
	creature: Creature;
	changeHP: (id: number, hp: number) => void;
	changeName: (id: number, name: string) => void;
	removeFromOrder: (id: number) => void;
}

export const CreatureTracker = ({
	creature,
	changeHP,
	changeName,
	removeFromOrder,
}: Props) => {
	const { init, name, isPlayer, HP, id } = creature;

	function handleHPChange(e: any) {
		const newHP = parseInt(e.target.value);

		if (newHP <= 0) {
			return removeFromOrder(id);
		}

		changeHP(id, newHP);
	}

	return (
		<div
			className={`init-creature ${isPlayer ? 'player' : 'creature'}`}
			data-testid={`creature-${isPlayer ? 'pc' : 'npc'}`}>
			<div className="init-number" data-testid="creature-init">
				{init}
			</div>
			<input
				type="text"
				name="Creature Name"
				className="pretty-input creature-name-input"
				value={name}
				onChange={(e) => changeName(id, e.target.value)}
				data-testid="creature-name"
			/>
			{!isPlayer && (
				<>
					<label htmlFor={`Creature-HP-${id}`} style={{ fontWeight: 'normal' }}>
						HP
					</label>
					<input
						type="number"
						name="Creature-HP"
						id={`Creature-HP-${id}`}
						min="0"
						className="pretty-input creature-hp"
						value={HP}
						onChange={handleHPChange}
					/>
				</>
			)}
		</div>
	);
};

// src/components/CreatureTracker.vue
<template>
  <div
    :class="`initCreature ${creature.isPlayer ? 'player' : 'creature'}`"
    :data-testid="`creature-${creature.isPlayer ? 'pc' : 'npc'}`"
  >
    <div className="init-number" data-testid="creature-init">
      {{ creature.init }}
    </div>
    <input
      type="text"
      name="Creature Name"
      class="pretty-input creature-name-input"
      :value="creature.name"
      @change="(e) => changeName(creature.id, e.target.value)"
      data-testid="creature-name"
    />
    <div v-if="isPlayer">
      <label
        :htmlFor="`Creature-HP-${creature.id}`"
        style="font-weight: normal"
      >
        HP
      </label>
      <input
        type="number"
        name="Creature-HP"
        :id="`Creature-HP-${creature.id}`"
        min="0"
        class="pretty-input creature-hp"
        :value="creature.HP"
        @change="handleHPChange"
      />
    </div>
  </div>
</template>

<script>
export default {
  props: ["creature"],
  methods: { handleHPChange() {}, changeName() {} }
};
</script>

<style>
.init-creature {
  display: flex;
  width: 80%;
  margin-bottom: 5px;
  list-style: none;
  padding: 5px 10px;
  border: var(--default-border);
  border-radius: var(--border-radius);
  font-weight: bold;
}

.init-number {
  width: 40px;
  padding: 5px;
  border-radius: 5px;
}

.creature {
  align-self: flex-end;
  background: lightpink;
}

.creature-hp {
  width: 50px;
  text-align: center;
}

.max-hp {
  width: 50px;
  text-align: center;
}

.player {
  background: lightgreen;
}

.creature-name-input {
  font-weight: bold;
  width: 40%;
}
</style>
